---
# Description
#   The Sensu VictorOps Handler is a Sensu Event Handler that alerts to
#   the VictorOps incident reponse service.
#
# Instructions
#   1. Add "victorops" to the "incident-management" handler set.
#
#      To create the "incident-management" handler set, please run:
#
#      $ sensuctl handler create incident-management --type set --handlers victorops
#
#      If you already have a handler set called "incident-management", please run:
#
#      $ sensuctl edit handler incident-management
#
#      NOTE: the sensuctl edit command will open your default editor; please
#      modify the "handlers" attribute by adding "victorops".
#
#   2. Configure the following secrets using your preferred Sensu Go Secrets
#      provider:
#
#      - victorops_routingkey
#
#      NOTE: example secret resources using the "env" provider are included in
#      this template; to add your secrets to the Sensu Backend, please modify
#      /etc/default/sensu-backend or /etc/sysconfig/sensu-backend and restart
#      the sensu-backend service.
#
#   3. More configuration options are available for this plugin; please see the
#      plugin documentation for more details.
#
# Documentation
#   - https://github.com/nixwiz/sensu-victorops-handler#sensu-victorops-handler
#   - https://docs.sensu.io/sensu-go/latest/reference/secrets/
#
# Contributors
#   The following individuals have contributed to this configuration template:
#   - Todd Campbell, @nixwiz
type: Handler
api_version: core/v2
metadata:
  name: victorops
  labels:
    jenkins_managed: "yes"
spec:
  command: sensu-victorops-handler
  env_vars: null
  filters:
  - is_incident
  - not_silenced
  handlers: null
  runtime_assets:
  - nixwiz/sensu-victorops-handler:0.1.2
  secrets:
  - name: SENSU_VICTOROPS_ROUTINGKEY
    secret: victorops_routingkey
  timeout: 0
  type: pipe
---
type: Secret
api_version: secrets/v1
metadata:
  name: victorops_routingkey
  labels:
    jenkins_managed: "yes"
spec:
  provider: env
  id: VICTOROPS_ROUTINGKEY
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/nixwiz/sensu-victorops-handler
    io.sensu.bonsai.name: sensu-victorops-handler
    io.sensu.bonsai.namespace: nixwiz
    io.sensu.bonsai.tags: handler
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/nixwiz/sensu-victorops-handler
    io.sensu.bonsai.version: 0.1.2
  name: nixwiz/sensu-victorops-handler:0.1.2
  namespace: default
  labels:
    jenkins_managed: "yes"
spec:
  builds:
  - filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: b5c8e9ff4ed708405cca5c1866d44699199a62a4bd97ec40ea4caafc69c80140879f591586310ba8a96bb60068d986f4304a734280588039c80aa4d6a28d2c75
    url: https://assets.bonsai.sensu.io/5b0394a5330c558b1c87c5eb22c17ac2d423231c/sensu-victorops-handler_0.1.2_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: c9dc592c34b7b25b95f4c514d1bb82abb0d2989cf893c79d767ce008d48f14d9c55a608627e8fe6120a2dda47b11388858e037a85927f5303c2e6a3f486831bd
    url: https://assets.bonsai.sensu.io/5b0394a5330c558b1c87c5eb22c17ac2d423231c/sensu-victorops-handler_0.1.2_darwin_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'armv7'
    headers: null
    sha512: 8495e2d5737b82ca44b3d91c2247edb8e592b2f6bc6f32208a615642b4c4e6473baa0cff6f25a55667f8977ebba083b2d6932af390dae1d986d91930ea072dbe
    url: https://assets.bonsai.sensu.io/5b0394a5330c558b1c87c5eb22c17ac2d423231c/sensu-victorops-handler_0.1.2_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: d86ef6072becdc5140fe690535633cf28ee3e632a010351d39452d129bd3a965f8427f643204a98c692da5c80b4850951d56b85470b6700b556aff4f8ad33437
    url: https://assets.bonsai.sensu.io/5b0394a5330c558b1c87c5eb22c17ac2d423231c/sensu-victorops-handler_0.1.2_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: 4abdacd9e66fbfef10e4c63a6d298f4613e02be41c9c074f71fdee19c403f9be52484b5f3c7b969dbc8f82dbf5d49c18f77b255843e58e5528a9a076a025a09e
    url: https://assets.bonsai.sensu.io/5b0394a5330c558b1c87c5eb22c17ac2d423231c/sensu-victorops-handler_0.1.2_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: f4f422e82620822eabf2218414952dbf090575c09455ce41fd819f2bbd9d0289ed9e772f8f6cdeaa343d753aa54d9708cde2f846d3544da0fc47835ca847ff4c
    url: https://assets.bonsai.sensu.io/5b0394a5330c558b1c87c5eb22c17ac2d423231c/sensu-victorops-handler_0.1.2_linux_amd64.tar.gz
  filters: null
  headers: null
